// <auto-generated />
using System;
using API.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190903142907_BananaMigration2")]
    partial class BananaMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<Guid>("EmailConfirmationToken");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<Guid>("PassworResetToken");

                    b.Property<string>("Password");

                    b.Property<byte[]>("Salt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8cec4b25-4563-463f-a690-498f60c743e9"),
                            Email = "user@email.com",
                            EmailConfirmationToken = new Guid("a6a46a35-5165-4ab5-9e19-12764cfc2144"),
                            EmailConfirmed = false,
                            PassworResetToken = new Guid("00000000-0000-0000-0000-000000000000"),
                            Password = "QWZjuWqZvjVItYJyHQc69LHCeYguawJdYgvELNszsdI=",
                            Salt = new byte[] { 23, 69, 221, 70, 219, 2, 73, 116, 196, 47, 121, 144, 89, 11, 131, 74 },
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
