// <auto-generated />
using System;
using API.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20190903121054_BananaMigration1")]
    partial class BananaMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<Guid>("EmailConfirmationToken");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Password");

                    b.Property<byte[]>("Salt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3572bc96-2536-4f22-b69a-ed89ae4f7d66"),
                            Email = "user@email.com",
                            EmailConfirmationToken = new Guid("a6a46a35-5165-4ab5-9e19-12764cfc2144"),
                            EmailConfirmed = false,
                            Password = "Z+rTKRldeJu7FKNCXwZF41l8I0plylCl2qwd0nxPGNg=",
                            Salt = new byte[] { 63, 145, 25, 252, 219, 98, 134, 192, 254, 198, 168, 251, 41, 32, 117, 121 },
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
